aula1/urls.py
from django.urls import include, path
from .  import views

app_name = 'aula1'

urlpatterns = [
    path('calculadora/', views.index, name='index'),
    path('screen/', views.screen, name='screen'),
    path('', views.screen, name='screen'),
    path('screen2/', views.screen2, name='screen2'),
    path('screen3/', views.screen3, name='screen3'),

]

my_app/urls.py
from django.urls import include, path
from . import views

app_name = 'my_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('filmes_v2/', views.filmes_v2, name='films_v2'),
    path('films14/', views.films14, name='films14'),
    path('films58/', views.films58, name='films58'),
    path('home/', views.home, name='home'),
    path('details/', views.details, name='details'),
    path('help/', views.help, name='help'),
    path('aula-table/', views.table, name='table'),
    path('form/', views.form, name='form'),
    path('topico/create/', views.model_form_topico, name='topico-create'),
]

mysitetest/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [

    path('my_app/', include('my_app.urls')),
    path('aula1/', include('aula1.urls')),
    path('', include('aula1.urls')),
    path('saopaulo/', include('saopaulo.urls')),
    path('admin/', admin.site.urls),
]

saopaulo/urls.py
from django.urls import include, path
from . import views

app_name = 'saopaulo'

urlpatterns = [
    path('', views.index, name='index'),
]

aula1/models.py
from django.db import models

# Create your models here.

my_app/models.py
from django.db import models

# Create your models here.
class Topico(models.Model):
    nome = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.nome

class WebPage(models.Model):
    topico = models.ForeignKey(Topico, on_delete=models.CASCADE)
    nome = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.nome

class RegistroAcesso(models.Model):
    pagina = models.ForeignKey(WebPage, on_delete=models.CASCADE)
    data = models.DateField()

    def __str__(self):
        return str(self.data)

    @classmethod
    def order_by(cls, param):
        pass

saopaulo/models.py
from django.db import models

# Create your models here.

my_app/forms.py
from django import forms

from my_app.models import Topico


class Form(forms.Form):
        nome = forms.CharField()
        email = forms.EmailField()
        texto = forms.CharField(widget=forms.Textarea)

class ModelFormTopico(forms.ModelForm):
        class Meta:
                model = Topico
                fields = "__all__"

aula1/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

def screen(request):
    return render(request, 'screen.html')

def screen2(request):
    return render(request, 'screen2.html')

def screen3(request):
    return render(request, 'screen3.html')

my_app/views.py
from django.http import HttpResponse
from django.shortcuts import render
from my_app.models import RegistroAcesso
# Create your views here.
from .forms import Form, ModelFormTopico


def index(request):
    return render(request, 'filmes.html')


def home(request):
    return render(request, 'home.html')

def filmes_v2(request):
    return render(request, 'filmes_v2.html')

def details(request):
    return render(request, 'details.html')

def help(request):
    return render(request, 'help.html')

def films14(request):
    return render(request, 'filmes14.xml')

def films58(request):
    return render(request, 'filmes58.json')

def table(request):
    listar_paginas = RegistroAcesso.objects.order_by('data')
    dict_lista = {"lista_acessos": listar_paginas}
    return render(request, 'aula_table.html', dict_lista)

def form(request):
    form = Form()

    if request.method == 'POST':
        form = Form(request.POST)
        if form.is_valid():
            print("Os campos estão corretos")
            print("Nome: "+ form.cleaned_data['nome'])
            print("Email: "+ form.cleaned_data['email'])
            print("Texto: "+ form.cleaned_data['texto'])
        else:
            print('erro')
    return render(request, 'forms.html', {'form': form})

def model_form_topico(request):
    topico = ModelFormTopico()
    if request.method == 'POST':
        topico = ModelFormTopico(request.POST)
        if topico.is_valid():
            print("Os campos estão corretos")
            print("Nome: "+ topico.cleaned_data['nome'])
            topico.save(commit=True)
        else:
            print('erro')
    return render(request, 'modelformtopico.html', {'topico': topico})

saopaulo/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'Untitled-1.html')

aula1/templates/index.html
{% extends 'layout.html' %}
{% load static %}
{% block body_block %}
    <table border="3">
            <tr>
                <td colspan="12">
                    <input type="text" id="result" minlength="0" maxlength="5" size="5" inputmode="numeric">
                    <input type="text" id="resulthide" minlength="0" maxlength="5" size="5" inputmode="numeric" hidden>
                </td>
            </tr>
            <tr>
                <td colspan="4"><input type="button" onClick="clr()" value="C"></td>
                <td colspan="4"><input type="button" onClick="dis('.')" value="."></td>
                <td colspan="4"><input type="button" onClick="dis('/')" value="/"></td>
            </tr>
            <tr>
                <td colspan="4"><input type="button" onClick="dis('+')" value="+"></td>
                <td colspan="4"><input type="button" onClick="dis('-')" value="-"></td>
                <td colspan="4"><input type="button" onClick="dis('*')" value="*"></td>
            </tr>
            <tr>
                <td colspan="4"><input type="button" onClick="dis('7')" value="7"></td>
                <td colspan="4"><input type="button" onClick="dis('8')" value="8"></td>
                <td colspan="4"><input type="button" onClick="dis('9')" value="9"></td>
            </tr>
            <tr>
                <td colspan="4"><input type="button" onClick="dis('4')" value="4"></td>
                <td colspan="4"><input type="button" onClick="dis('5')" value="5"></td>
                <td colspan="4"><input type="button" onClick="dis('6')" value="6"></td>
            </tr>
            <tr>
                <td colspan="4"><input type="button" onClick="dis('1')" value="1"></td>
                <td colspan="4"><input type="button" onClick="dis('2')" value="2"></td>
                <td colspan="4"><input type="button" onClick="dis('3')" value="3"></td>
            </tr>
            <tr>
                <td colspan="4"><input type="button" onClick="convert()" value="+/-"></td>
                <td colspan="4"><input type="button" onClick="dis('0')" value="0"></td>
                <td colspan="4"><input type="button" onClick="solve()" value="="></td>
            </div>
            </tr>
        </table>
{% endblock %}

aula1/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <title>Screen</title>
        <link rel="stylesheet" href="{% static "css/calculator_style.css" %}">
    </head>
    <body>
       <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{%  url 'aula1:screen' %}">
                <img src="{% static "css/images/hp_avatar.png" %}" width="30" height="30" alt="avatar">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item active">
                    <a class="nav-link" href="{%  url 'aula1:screen' %}">Pagina 1</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{%  url 'aula1:screen2' %}">Pagina 2</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{%  url 'aula1:screen3' %}">Pagina 3</a>
                  </li> <li class="nav-item">
                    <a class="nav-link" href="{%  url 'aula1:index' %}">Calculadora</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{%  url 'saopaulo:index' %}">São Paulo</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{%  url 'my_app:index' %}">Filmes Harry Potter</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{%  url 'my_app:topico-create' %}">Form do Tópico</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{%  url 'my_app:form' %}">Forms</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{%  url 'my_app:details' %}">Detalhes</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{%  url 'my_app:help' %}">Ajuda</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{%  url 'my_app:table' %}">Tabela</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/admin">Login Admin</a>
                  </li>
                </ul>
            </div>
        </nav>
        {% block body_block %}

        {% endblock %}
        <footer class="position-fixed w-100 text-white bg-dark text-center fixed-bottom">
            <h3>Página HTML desenvolvida por Cadmiel©</h3>
        </footer>
    </body>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static "js/calculator.js" %}"></script>
</html>

aula1/templates/screen.html
<!DOCTYPE html>
{% extends 'layout.html' %}

{% block body_block %}
     <h1 class="w-100 text-center">Você está na pagina 1</h1>
    <div class="text-center">
        <div class="col-md-12">
            {% filter force_escape|length %}
                Numero de Caracteres
            {% endfilter %}
        </div>
        <div class="col-md-12">
            {% filter force_escape|lower %}
                Frase em LowerCase
            {% endfilter %}
        </div>
        <div class="col-md-12">
            {% filter force_escape|upper %}
                Frase em UperCase
            {% endfilter %}
        </div>
    </div>



{% endblock %}

aula1/templates/screen2.html
<!DOCTYPE html>
{% extends 'layout.html' %}

{% block body_block %}
    <h1 class="w-100 text-center">Você está na pagina 2</h1>
{% endblock %}

aula1/templates/screen3.html
<!DOCTYPE html>
{% extends 'layout.html' %}

{% block body_block %}
 <h1 class="w-100 text-center">Você está na pagina 3</h1>
{% endblock %}

my_app/templates/aula_table.html
{% extends 'layout.html' %}
{% load static %}
{% block body_block %}
{% if lista_acessos %}
<table class="table-bordered table-striped w-100">
    <thead>
        <th>Nome da pagina</th>
        <th>Data de acesso</th>
    </thead>
    <tbody>
    {% for acesso in lista_acessos %}
        <tr>
            <td>{{ acesso.pagina }}</td>
            <td>{{ acesso.data }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endif %}
{% endblock %}

my_app/templates/details.html
{% extends 'layout.html' %}
{% load static %}
{% block body_block %}
    <h1>Detalhes Data de hoje {% now "SHORT_DATETIME_FORMAT" %}</h1>
    <img src="{% static '/css/images/urso3d.jpeg' %}" alt="My image">
{% endblock %}

my_app/templates/filmes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static "css/index.css" %}">
        <link rel="stylesheet" href="{% static "css/filmes.css" %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <title>A Harry Potter Website</title>
    </head>
    <body>
        <div class="allpage">
            <div class="menu">
                <nav>
                    <a href="{%  url 'my_app:home' %}">Home</a>
                    <a href="{%  url 'saopaulo:index' %}">São Paulo</a>
                    <a href="{%  url 'aula1:index' %}">Calculadora</a>
                    <a href="{%  url 'my_app:films_v2' %}">Filmes v2</a>
                    <a href="{%  url 'my_app:index' %}">Filmes</a>
                    <a href="{%  url 'my_app:table' %}">Tabela</a>
                    <a href="#"><img src="{% static "css/images/hp_avatar.png" %}" alt="avatar"></a>
                </nav>
            </div>
            <div class="conteudo">
                <div class="imagem-fundo"></div>

                <div class="todos-filmes">
                    <div class="linha-filmes">
                        <div class="filme" id="filme1">
                            <div class="capa">
                                <img src="{% static "css/images/hp1_filme.jpg" %}" alt="">
                            </div>
                            <div class="infos">
                                <p class="titulo">Harry Potter e a Pedra Filosofal</p>
                                <p class="ano">2001</p>
                                <p class="diretor">Chris Colombus</p>
                                <p class="sinopse">Harry Potter (Daniel Radcliffe) é um garoto órfão de 10 anos que vive infeliz com seus tios, os Dursley. Até que, repentinamente, ele recebe uma carta contendo um convite para ingressar em Hogwarts, uma famosa escola especializada em formar jovens bruxos. Inicialmente Harry é impedido de ler a carta por seu tio Válter (Richard Griffiths), mas logo ele recebe a visita de Hagrid (Robbie Coltrane), o guarda-caça de Hogwarts, que chega em sua casa para levá-lo até a escola. A partir de então Harry passa a conhecer um mundo mágico que jamais imaginara, vivendo as mais diversas aventuras com seus mais novos amigos, Rony Weasley (Rupert Grint) e Hermione Granger (Emma Watson).</p>
                            </div>
                        </div>
                        <div class="filme" id="filme2">
                            <div class="capa">
                                <img src="{% static "css/images/hp2_filme.jpg" %}" alt="">
                            </div>
                            <div class="infos">
                                <p class="titulo">Harry Potter e a Câmara Secreta</p>
                                <p class="ano">2002</p>
                                <p class="diretor">Chris Colombus</p>
                            </div>
                        </div>
                        <div class="filme">
                            <div class="capa">
                                <img src="{% static "css/images/hp3_filme.jpg" %}" alt="">
                            </div>
                            <div class="infos">
                                <p class="titulo">Harry Potter e o Prisioneiro de Azkaban</p>
                                <p class="ano">2004</p>
                                <p class="diretor">Alfonso Cuarón</p>
                            </div>
                        </div>
                        <div class="filme">
                            <div class="capa">
                                <img src="{% static "css/images/hp4_filme.webp" %}" alt="">
                            </div>
                            <div class="infos">
                                <p class="titulo">Harry Potter e o Cálice de Fogo</p>
                                <p class="ano">2005</p>
                                <p class="diretor">Mike Newell</p>
                            </div>
                        </div>
                    </div>
                    <div class="linha-filmes">
                        <div class="filme">
                            <div class="capa">
                                <img src="{% static "css/images/hp5_filme.webp" %}" alt="">
                            </div>
                            <div class="infos">
                                <p class="titulo">Harry Potter e a Ordem da Fênix</p>
                                <p class="ano">2007</p>
                                <p class="diretor">David Yates</p>
                            </div>
                        </div>
                        <div class="filme">
                            <div class="capa">
                                <img src="{% static "css/images/hp6_filme.jpg" %}" alt="">
                            </div>
                            <div class="infos">
                                <p class="titulo">Harry Potter e o Enigma do Príncipe</p>
                                <p class="ano">2009</p>
                                <p class="diretor">David Yates</p>
                            </div>
                        </div>
                        <div class="filme">
                            <div class="capa">
                                <img src="{% static "css/images/hp71_filme.jpg" %}" alt="">
                            </div>
                            <div class="infos">
                                <p class="titulo">Harry Potter e as Relíquias da Morte: Parte 1</p>
                                <p class="ano">2010</p>
                                <p class="diretor">David Yates</p>
                            </div>
                        </div>
                        <div class="filme">
                            <div class="capa">
                                <img src="{% static "css/images/hp72_filme.jpg" %}" alt="">
                            </div>
                            <div class="infos">
                                <p class="titulo">Harry Potter e as Relíquias da Morte: Parte 2</p>
                                <p class="ano">2011</p>
                                <p class="diretor">David Yates</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="visualiza-direito">
                    <div id="msg-direito">
                        <p>Clique em um filme para exibir mais detalhes!</p>
                    </div>
                    <div id="conteudo-direito">
                        <p id="visualiza-titulo">Harry Potter e as Relíquias da Morte: Parte 2</p>
                        <img id="visualiza-imagem" src="{% static "css/images/hp72_filme.jpg" %}" alt="">
                        <p id="visualiza-ano-diretor">2011 - David Yates</p>
                        <p id="visualiza-sinopse">Harry Potter (Daniel Radcliffe) e seus amigos Rony Weasley (Rupert Grint) e Hermione Granger (Emma Watson) seguem à procura das horcruxes. O objetivo do trio é encontrá-las e, em seguida, destruí-las, de forma a eliminar lorde Voldemort (Ralph Fiennes) de uma vez por todas. Com a ajuda do duende Grampo (Warwick Davis), eles entram no banco Gringotes de forma a invadir o cofre de Bellatrix Lestrange (Helena Bonham Carter). De lá retornam ao castelo de Hogwarts, onde precisam encontrar mais uma horcrux. Paralelamente, Voldemort prepara o ataque definitivo ao castelo.</p>
                    </div>
                </div>
            </div>
            <div class="rodape">
                <p>Página HTML desenvolvida por Lucas B. Galhardi ©</p>
            </div>
        </div>
        <script src="{% static "js/filmes.js" %}"></script>
    </body>
</html>

my_app/templates/filmes_v2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/index.css" %}">
    <link rel="stylesheet" href="{% static "css/filmes.css" %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>A Harry Potter Website</title>
</head>
<body>
<div class="allpage">
    <div class="menu">
        <nav>
            <a href="{%  url 'my_app:home' %}">Home</a>
            <a href="{%  url 'saopaulo:index' %}">São Paulo</a>
            <a href="{%  url 'aula1:index' %}">Calculadora</a>
            <a href="{%  url 'my_app:films_v2' %}">Filmes v2</a>
            <a href="{%  url 'my_app:index' %}">Filmes</a>
            <a href="{%  url 'my_app:table' %}">Tabela</a>
            <a href="#"><img src="{% static "css/images/hp_avatar.png" %}" alt="avatar"></a>
        </nav>
    </div>
    <div class="conteudo">
        <div class="imagem-fundo"></div>
        <div class="todos-filmes">
            <div class="linha-filmes">
                <div class="filme">
                    <div class="capa"><img src="" alt=""></div>
                    <div class="infos">
                        <p class="titulo"></p>
                        <p class="diretor"></p>
                        <p class="ano"></p>
                    </div>
                </div>
                <div class="filme">
                    <div class="capa"><img src="" alt=""></div>
                    <div class="infos">
                        <p class="titulo"></p>
                        <p class="diretor"></p>
                        <p class="ano"></p>
                    </div>
                </div>
                <div class="filme">
                    <div class="capa"><img src="" alt=""></div>
                    <div class="infos">
                        <p class="titulo"></p>
                        <p class="diretor"></p>
                        <p class="ano"></p>
                    </div>
                </div>
                <div class="filme">
                    <div class="capa"><img src="" alt=""></div>
                    <div class="infos">
                        <p class="titulo"></p>
                        <p class="diretor"></p>
                        <p class="ano"></p>
                    </div>
                </div>
            </div>
            <div class="linha-filmes">
                <div class="filme">
                    <div class="capa"><img src="" alt=""></div>
                    <div class="infos">
                        <p class="titulo"></p>
                        <p class="diretor"></p>
                        <p class="ano"></p>
                    </div>
                </div>
                <div class="filme">
                    <div class="capa"><img src="" alt=""></div>
                    <div class="infos">
                        <p class="titulo"></p>
                        <p class="diretor"></p>
                        <p class="ano"></p>
                    </div>
                </div>
                <div class="filme">
                    <div class="capa"><img src="" alt=""></div>
                    <div class="infos">
                        <p class="titulo"></p>
                        <p class="diretor"></p>
                        <p class="ano"></p>
                    </div>
                </div>
                <div class="filme">
                    <div class="capa"><img src="" alt=""></div>
                    <div class="infos">
                        <p class="titulo"></p>
                        <p class="diretor"></p>
                        <p class="ano"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="visualiza-direito">
            <div id="msg-direito">
                <p>Clique em um filme para exibir mais detalhes!</p>
            </div>
            <div id="conteudo-direito">
                <p id="visualiza-titulo"></p>
                <img id="visualiza-imagem" src="" alt="">
                <p id="visualiza-ano-diretor"></p>
                <p id="visualiza-sinopse">Harry Potter (Daniel Radcliffe) e seus amigos Rony Weasley (Rupert Grint) e Hermione Granger (Emma Watson) seguem à procura das horcruxes. O objetivo do trio é encontrá-las e, em seguida, destruí-las, de forma a eliminar lorde Voldemort (Ralph Fiennes) de uma vez por todas. Com a ajuda do duende Grampo (Warwick Davis), eles entram no banco Gringotes de forma a invadir o cofre de Bellatrix Lestrange (Helena Bonham Carter). De lá retornam ao castelo de Hogwarts, onde precisam encontrar mais uma horcrux. Paralelamente, Voldemort prepara o ataque definitivo ao castelo.</p>
            </div>
        </div>
    </div>
    <div class="rodape">
        <p>Página HTML desenvolvida por Lucas B. Galhardi ©</p>
    </div>
</div>
<script src="{% static "js/filmes.js" %}"></script>
</body>
</html>

my_app/templates/forms.html
{% extends 'layout.html' %}
{% load static %}
{% block body_block %}
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="submit">
    </form>
{% endblock %}

my_app/templates/help.html
{% extends 'layout.html' %}
{% load static %}
{% block body_block %}
    <h1>Help Data de hoje {% now "SHORT_DATETIME_FORMAT" %}</h1>
{% endblock %}

my_app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static "css/index.css" %}">
        <title>A Harry Potter Website</title>
    </head>
    <body>
        <div class="allpage">
            <div class="menu">
                <nav>
                    <a href="{%  url 'my_app:home' %}">Home</a>
                    <a href="{%  url 'saopaulo:index' %}">São Paulo</a>
                    <a href="{%  url 'aula1:index' %}">Calculadora</a>
                    <a href="{%  url 'my_app:films_v2' %}">Filmes v2</a>
                    <a href="{%  url 'my_app:index' %}">Filmes</a>
                    <a href="{%  url 'my_app:table' %}">Tabela</a>
                    <a href="#"><img src="{% static "css/images/hp_avatar.png" %}" alt="avatar"></a>
                </nav>
            </div>
            <div class="conteudo">
                <div class="imagem-fundo"></div>
                <p class="home">Navegue pelo menu e conheça esse mundo mágico</p>
            </div>
            <div class="rodape">
                <p>Página HTML desenvolvida por Lucas B. Galhardi ©</p>
            </div>
        </div>
    </body>
</html>

my_app/templates/modelformtopico.html
{% extends 'layout.html' %}
{% load static %}
{% block body_block %}
    <form method="post">
        {{ topico.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="submit">
    </form>
{% endblock %}

saopaulo/templates/Untitled-1.html
{%  extends "app.html" %}
{% block body_block %}
    <div class="row">
        <h1>O que eu mais gosto em São Paulo</h1>
        <div class="container">
            <h2>Passear na Avenida Paulista</h2>
            <img src="https://media-cdn.tripadvisor.com/media/photo-s/18/99/d8/ed/paulista.jpg">
            <p>
                Um dos principais centros financeiros da cidade, a avenida Paulista 
                também possui diversas opções de entretenimento. Endereço do Museu
                de Arte de São Paulo, MASP, do Teatro Gazeta e muitos outros,
                a região é de fácil acesso graças as diversas linhas de ônibus que
                cruzam a avenida e a linha de metrô que passa por baixo dela.
            </p>
            <p>
                A avenida paulista sempre é assunto. O que será que estão falando a respeito
                no <a href="https://twitter.com/search?q=Avenida Paulista">Twitter</a>
            </p>
        </div>
        <div class="container">
            <h2>Os bares da vila Madalena</h2>
            <img src="https://www.guiadasemana.com.br/contentFiles/image/opt_w840h0/2019juliana/lugares/vila-madalena/28060886-1719018988119237-4294555165498106193-o.jpg">
            <p>
                Depois de um dia de trabalho, nada melhor do que um bom chopp, um
                petisco e uma conversa em uma mesa de bar. Opções de sobra na região
                das ruas Aspicuelta, Fradique Coutinho e Wisard.
            </p>
            <p>
                Veja quais os melhores bares e restaurantes da região no
               <a href="https://vejasp.abril.com.br/cidades/melhor-da-vila-madalena-restaurantes/">Guia da VEJA São Paulo.</a>
            </p>
        </div>
        <div class="container">
            <h2>O parque do Ibirapuera</h2>
            <img src="https://abrilexame.files.wordpress.com/2019/03/parque-do-ibirapuera.gif">
            <p>
                Um dos cartões postais da cidade, o parque dispõe de mais de 1,5 km{^2}
                de área verde, lagos artificiais e pistas de cooper e ciclismo. E se
                isso não fosse o suficiente, o parque costuma ser palco de diversos
                eventos culturais ao longo do ano. 
            </p>
            <p>
                Veja no <a href="http://goo.gl/maps/HoH8">mapa</a> 
                como chegar ao parque.
            </p>
        </div>
        <div class="finishmenu">
            <h3>E existem muitos outros lugares interessantes na cidade...</h3>
            <ol>
                <li>
                    O Mercado Municipal.
                </li>
                <li>
                    A Sala São Paulo
                </li>
                <li>Os Principais estadios dos principais times de futebol da cidade</li>
                <li>Diversos museus como o Memorial da América Latina, Museu da Lingua Portuguesa e o Museu do Ipiranga</li>
                <li>E mais!</li>
            </ol>
        </div>
        <div class="footer">
            Parte do livro "HTML5 e CSS3: Domine a web do futuro"
        </div>
    </div>
{%  endblock %}

saopaulo/templates/app.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static "css/cap2.css" %}">
    <title>Aula Web</title>
</head>
<body>
    {% block body_block %}

    {% endblock %}
</body>
</html>